In [1]:
import numpy as np

In [2]:
print('\n\n----- One-hot vector representation of nodes. Shape(n,n)\n')
X = np.eye(5, 5)
n = X.shape[0]
np.random.shuffle(X)
print(X)



----- One-hot vector representation of nodes. Shape(n,n)

[[0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]]


In [3]:
print('\n\n----- Embedding dimension\n')
emb = 3
print(emb)

print('\n\n----- Weight Matrix. Shape(emb, n)\n')
W = np.random.uniform(-np.sqrt(1. / emb), np.sqrt(1. / emb), (emb, n))
print(W)



----- Embedding dimension

3


----- Weight Matrix. Shape(emb, n)

[[ 0.07930732 -0.11725941 -0.1673762  -0.16321515  0.22484854]
 [-0.53400189  0.26403632  0.46395198  0.09034165  0.37060727]
 [-0.51256579 -0.32878073  0.57647127 -0.05172605  0.20563797]]


In [4]:
print('\n\n----- Adjacency Matrix (undirected graph). Shape(n,n)\n')
A = np.random.randint(2, size=(n, n))
np.fill_diagonal(A, 1)  
A = (A + A.T)
A[A > 1] = 1
print(A)



----- Adjacency Matrix (undirected graph). Shape(n,n)

[[1 1 0 0 1]
 [1 1 1 0 1]
 [0 1 1 1 1]
 [0 0 1 1 1]
 [1 1 1 1 1]]


In [5]:
# equation (1)
print('\n\n----- Linear Transformation. Shape(n, emb)\n')
z1 = X.dot(W.T)
print(z1)



----- Linear Transformation. Shape(n, emb)

[[-0.11725941  0.26403632 -0.32878073]
 [-0.16321515  0.09034165 -0.05172605]
 [-0.1673762   0.46395198  0.57647127]
 [ 0.07930732 -0.53400189 -0.51256579]
 [ 0.22484854  0.37060727  0.20563797]]


In [6]:
# equation (2) - First part
print('\n\n----- Concat hidden features to represent edges. Shape(len(emb.concat(emb)), number of edges)\n')
edge_coords = np.where(A==1)
h_src_nodes = z1[edge_coords[0]]
h_dst_nodes = z1[edge_coords[1]]
z2 = np.concatenate((h_src_nodes, h_dst_nodes), axis=1)



----- Concat hidden features to represent edges. Shape(len(emb.concat(emb)), number of edges)

